
# ===============================
# = H2 Database (Development)
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# = JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.use_sql_comments=true

# H2 Console (optional)
spring.h2.console.enabled=true

# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

server.forward-headers-strategy=framework
server.tomcat.redirect-context-root=false
server.tomcat.use-relative-redirects=true
# = Server Config
# ===============================
server.port=8080
